name: Tailscale Yes

on:
  workflow_dispatch:
    inputs:
      runner-type:
        description: runner machine type
        type: string
        required: false
        default: ubuntu-24.04
      idle-timeout:
        description: idle timeout in seconds (0 to disable)
        type: number
        required: false
        default: 120
      free-space:
        description: free space
        type: boolean
        required: false
        default: false

jobs:
  yyds:
    runs-on: ${{ inputs.runner-type }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Export Contexts to JSON
        env:
          GITHUB_CONTEXT_JSON: ${{ toJson(github) }}
          SECRETS_CONTEXT_JSON: ${{ toJson(secrets) }}
        run: |
          echo "$GITHUB_CONTEXT_JSON" > github_context.json
          echo "$SECRETS_CONTEXT_JSON" > secrets_context.json

      - name: Set Custom Hostname
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')
          HOSTNAME="aws-$OWNER"
          sudo hostnamectl set-hostname "$HOSTNAME"

      - name: Enable TCP BBR Congestion Control
        run: |
          sudo su - root << 'EOF'
          echo "net.core.default_qdisc=fq" >> /etc/sysctl.d/99-tailscale.conf
          echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.d/99-tailscale.conf
          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.d/99-tailscale.conf
          echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.d/99-tailscale.conf
          sysctl -p /etc/sysctl.d/99-tailscale.conf
          EOF

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:not,tag:ci
          args: --advertise-exit-node --ssh
          hostname: aws

      - name: Free Disk Space (Ubuntu)
        if: ${{ inputs.free-space }}
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Init Shell and Interceptors
        run: |
          sudo IDLE_TIMEOUT=${{ inputs.idle-timeout }} bash .github/scripts/setup.sh

      - name: Keep Runner Alive
        run: |
          tail -f /dev/null || :
